require 'rake'

task :default => :compile

desc 'Use dmcs to compile'
task :compile do
  sh "dmcs -r:OpenTK.dll -r:System.dll -r:System.Drawing.dll -r:../Renderer.dll -r:xunit.dll -out:RendererTest.dll -target:library *.cs"
end

desc 'Clean up the build'
task :clean do
  sh "rm RendererTest.dll *.xml"
end

desc 'Run unit tests'
task :test do
  puts %x(sh ~/xunit/xunit.sh RendererTest.dll //nunit TestResults.xml)
end
